### ISSUE TITLE
what happened

### ISSUE THREAD

**Issue by mijunhua** [LynnHo/DCGAN-LSGAN-WGAN-GP-DRAGAN-Tensorflow-2#13]
hello，When I run  train_mnist_wgan_gp.py, I encounter the following situation：
[*] Loading checkpoint...
 [*] No suitable checkpoint!
 [*] Close main session!
Could you help me see what happened and how to solve it?

**Comment by LynnHo** [comment]
@mijunhua maybe you should remove the try-catch-finally part to catch what happens in the train loop.
