### ISSUE TITLE
how about 3D data?

### ISSUE THREAD

**Issue by KakaVlasic** [LynnHo/DCGAN-LSGAN-WGAN-GP-DRAGAN-Tensorflow-2#14]
Hi!
 
# cartoon faces original size is [96, 96, 3],the number 3 means 3 channel RGB data. But if I have grayscale data with 3 slices, i.e the size is [121,145,3], Can I simply use this code? If not, what should I change based on this code?

Thanks for your work! Look forward to your response.

**Comment by LynnHo** [comment]
@KakaVlasic I think you can simply resize the data to [128, 128, 3], try the code and resize the data back to [121, 145, 3]. For 128*128 image, I suggest using WGAN-GP with 5 upsamplings. You may change some code below,
https://github.com/LynnHo/DCGAN-LSGAN-WGAN-GP-DRAGAN-Tensorflow-2/blob/d800affec129db41785a4f3128c2962447732469/train.py#L64-L73
https://github.com/LynnHo/DCGAN-LSGAN-WGAN-GP-DRAGAN-Tensorflow-2/blob/d800affec129db41785a4f3128c2962447732469/data.py#L82-L110

**Comment by KakaVlasic** [comment]
@LynnHo Thanks for you reply!
I run the code as you suggested, but I encounter this error, have you ever met?
![bug](https://user-images.githubusercontent.com/42176201/59612303-70a7cd80-914f-11e9-8fad-e2715e4efbe0.PNG)
![train](https://user-images.githubusercontent.com/42176201/59612311-730a2780-914f-11e9-85c7-ccf733175e3c.PNG)
![data](https://user-images.githubusercontent.com/42176201/59612312-730a2780-914f-11e9-9515-1a21e026e688.PNG)

**Comment by LynnHo** [comment]
@KakaVlasic I cannot find a problem. Maybe you can try to remove the line of `@tf.function`.
