### ISSUE TITLE
WGAN-GP does not work!!!

### ISSUE THREAD

**Issue by LynnHo** [LynnHo/DCGAN-LSGAN-WGAN-GP-DRAGAN-Tensorflow-2#15]
I have updated the code from TensorFlow 2.0-alpha to TensorFlow 2.0, everything works well except for WGAN-GP (it works in tf2.0-alpha). In tf2.0, The gradient penalty seems very unstable, but I cannot find out the problem. Does anybody help? I will be grateful.

**Comment by jaeseongyou** [comment]
Try removing training=True at 111, 112, 125, 127, 128 lines of 'train.py'
(e.g. x_fake = G(z) instead of x_fake = G(z, training=True) etc.)
I got it working with that trick.

**Comment by LynnHo** [comment]
@jaeseongyou Thanks a lot! I will try to figure out what 's wrong with `training=True`.

**Comment by LynnHo** [comment]
After updating to TF2.2, this problem disappears and WGAN-GP works great.
