### ISSUE TITLE
Error while using celeba dataset

### ISSUE THREAD

**Issue by yksolanki9** [LynnHo/DCGAN-LSGAN-WGAN-GP-DRAGAN-Tensorflow-2#17]
I am getting this error while running train.py
`TypeError: Input 'filename' of 'ReadFile' Op has type float32 that does not match expected type of string.`
Please help with this. Thanks in advance

**Comment by LynnHo** [comment]
@yksolanki9 It seems that the code does not find the data. Can you make sure that the images are put into the right place `./data/img_align_celeba/*.jpg`.

**Comment by yksolanki9** [comment]
That was helpful. Thank you!
