### ISSUE TITLE
A problem for your DCGAN architecture

### ISSUE THREAD

**Issue by RayGuo-C** [LynnHo/DCGAN-LSGAN-WGAN-GP-DRAGAN-Tensorflow-2#19]
Hi, - Your work is really interesting. 
But I have found there is a problem for your DCGAN that I didn't understand.
You generate noise twice when train discriminator and generator for each iteration, like the blue lines in the following picture. In soumith code (includes some official DCGAN code), he only generate noise once: https://github.com/soumith/dcgan.torch. Could you please tell me the reason?

![image](https://user-images.githubusercontent.com/34149368/134488630-c1c1f44c-c1e0-4c75-8084-d722ba46724f.png)

**Comment by LynnHo** [comment]
@RayGuo-C Because G and D training are separated，they don't need the same noise input.
